name: baresip

on:
  push:
    branches: [ main ]
    paths:
      - 'baresip/Dockerfile'
      - '.github/workflows/baresip.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'baresip/Dockerfile'
      - '.github/workflows/baresip.yml'

env:
  VERSION: 2.6.0
  IMAGE_NAME: ${{ github.repository }}/baresip

jobs:
  baresip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: docker build baresip -t baresip --build-arg version=${{ env.VERSION }}

    - name: Tag and Push image
      if: github.event_name != 'pull_request'
      run: |
        docker tag baresip ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker tag baresip ghcr.io/${{ env.IMAGE_NAME }}:latest
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:latest
